# coding: utf-8

"""
    StackExchange

    Stack Exchange is a network of 130+ Q&A communities including Stack Overflow. 

    The version of the OpenAPI document: 2.0
    Generated by: https://konfigthis.com
"""

import unittest

import os
from pprint import pprint
from stack_exchange_python_sdk import StackExchange

class TestSimple(unittest.TestCase):
    def setUp(self):
        pass

    def test_client(self):
        stackexchange = StackExchange(
        
            client_id = 'YOUR_CLIENT_ID',
            client_secret = 'YOUR_CLIENT_SECRET',
        )
        self.assertIsNotNone(stackexchange)

    def tearDown(self):
        pass


if __name__ == "__main__":
    unittest.main()
