# coding: utf-8

"""
    StackExchange

    Stack Exchange is a network of 130+ Q&A communities including Stack Overflow. 

    The version of the OpenAPI document: 2.0
    Generated by: https://konfigthis.com
"""

from datetime import date, datetime  # noqa: F401
import decimal  # noqa: F401
import functools  # noqa: F401
import io  # noqa: F401
import re  # noqa: F401
import typing  # noqa: F401
import typing_extensions  # noqa: F401
import uuid  # noqa: F401

import frozendict  # noqa: F401

from stack_exchange_python_sdk import schemas  # noqa: F401


class FiltersItem(
    schemas.DictSchema
):
    """
    This class is auto generated by Konfig (https://konfigthis.com)
    """


    class MetaOapg:
        
        class properties:
            filter = schemas.StrSchema
            filter_type = schemas.StrSchema
        
            @staticmethod
            def included_fields() -> typing.Type['FiltersItemIncludedFields']:
                return FiltersItemIncludedFields
            __annotations__ = {
                "filter": filter,
                "filter_type": filter_type,
                "included_fields": included_fields,
            }
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["filter"]) -> MetaOapg.properties.filter: ...
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["filter_type"]) -> MetaOapg.properties.filter_type: ...
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["included_fields"]) -> 'FiltersItemIncludedFields': ...
    
    @typing.overload
    def __getitem__(self, name: str) -> schemas.UnsetAnyTypeSchema: ...
    
    def __getitem__(self, name: typing.Union[typing_extensions.Literal["filter", "filter_type", "included_fields", ], str]):
        # dict_instance[name] accessor
        return super().__getitem__(name)
    
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["filter"]) -> typing.Union[MetaOapg.properties.filter, schemas.Unset]: ...
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["filter_type"]) -> typing.Union[MetaOapg.properties.filter_type, schemas.Unset]: ...
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["included_fields"]) -> typing.Union['FiltersItemIncludedFields', schemas.Unset]: ...
    
    @typing.overload
    def get_item_oapg(self, name: str) -> typing.Union[schemas.UnsetAnyTypeSchema, schemas.Unset]: ...
    
    def get_item_oapg(self, name: typing.Union[typing_extensions.Literal["filter", "filter_type", "included_fields", ], str]):
        return super().get_item_oapg(name)
    

    def __new__(
        cls,
        *args: typing.Union[dict, frozendict.frozendict, ],
        filter: typing.Union[MetaOapg.properties.filter, str, schemas.Unset] = schemas.unset,
        filter_type: typing.Union[MetaOapg.properties.filter_type, str, schemas.Unset] = schemas.unset,
        included_fields: typing.Union['FiltersItemIncludedFields', schemas.Unset] = schemas.unset,
        _configuration: typing.Optional[schemas.Configuration] = None,
        **kwargs: typing.Union[schemas.AnyTypeSchema, dict, frozendict.frozendict, str, date, datetime, uuid.UUID, int, float, decimal.Decimal, None, list, tuple, bytes],
    ) -> 'FiltersItem':
        return super().__new__(
            cls,
            *args,
            filter=filter,
            filter_type=filter_type,
            included_fields=included_fields,
            _configuration=_configuration,
            **kwargs,
        )

from stack_exchange_python_sdk.model.filters_item_included_fields import FiltersItemIncludedFields
