# coding: utf-8

"""
    StackExchange

    Stack Exchange is a network of 130+ Q&A communities including Stack Overflow. 

    The version of the OpenAPI document: 2.0
    Generated by: https://konfigthis.com
"""

from datetime import date, datetime  # noqa: F401
import decimal  # noqa: F401
import functools  # noqa: F401
import io  # noqa: F401
import re  # noqa: F401
import typing  # noqa: F401
import typing_extensions  # noqa: F401
import uuid  # noqa: F401

import frozendict  # noqa: F401

from stack_exchange_python_sdk import schemas  # noqa: F401


class InboxItemsItem(
    schemas.DictSchema
):
    """
    This class is auto generated by Konfig (https://konfigthis.com)
    """


    class MetaOapg:
        
        class properties:
            title = schemas.StrSchema
            answer_id = schemas.IntSchema
            body = schemas.StrSchema
            comment_id = schemas.IntSchema
            creation_date = schemas.IntSchema
            is_unread = schemas.BoolSchema
            item_type = schemas.StrSchema
            link = schemas.StrSchema
            question_id = schemas.IntSchema
        
            @staticmethod
            def site() -> typing.Type['InboxItemsItemSite']:
                return InboxItemsItemSite
            __annotations__ = {
                "title": title,
                "answer_id": answer_id,
                "body": body,
                "comment_id": comment_id,
                "creation_date": creation_date,
                "is_unread": is_unread,
                "item_type": item_type,
                "link": link,
                "question_id": question_id,
                "site": site,
            }
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["title"]) -> MetaOapg.properties.title: ...
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["answer_id"]) -> MetaOapg.properties.answer_id: ...
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["body"]) -> MetaOapg.properties.body: ...
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["comment_id"]) -> MetaOapg.properties.comment_id: ...
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["creation_date"]) -> MetaOapg.properties.creation_date: ...
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["is_unread"]) -> MetaOapg.properties.is_unread: ...
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["item_type"]) -> MetaOapg.properties.item_type: ...
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["link"]) -> MetaOapg.properties.link: ...
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["question_id"]) -> MetaOapg.properties.question_id: ...
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["site"]) -> 'InboxItemsItemSite': ...
    
    @typing.overload
    def __getitem__(self, name: str) -> schemas.UnsetAnyTypeSchema: ...
    
    def __getitem__(self, name: typing.Union[typing_extensions.Literal["title", "answer_id", "body", "comment_id", "creation_date", "is_unread", "item_type", "link", "question_id", "site", ], str]):
        # dict_instance[name] accessor
        return super().__getitem__(name)
    
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["title"]) -> typing.Union[MetaOapg.properties.title, schemas.Unset]: ...
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["answer_id"]) -> typing.Union[MetaOapg.properties.answer_id, schemas.Unset]: ...
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["body"]) -> typing.Union[MetaOapg.properties.body, schemas.Unset]: ...
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["comment_id"]) -> typing.Union[MetaOapg.properties.comment_id, schemas.Unset]: ...
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["creation_date"]) -> typing.Union[MetaOapg.properties.creation_date, schemas.Unset]: ...
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["is_unread"]) -> typing.Union[MetaOapg.properties.is_unread, schemas.Unset]: ...
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["item_type"]) -> typing.Union[MetaOapg.properties.item_type, schemas.Unset]: ...
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["link"]) -> typing.Union[MetaOapg.properties.link, schemas.Unset]: ...
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["question_id"]) -> typing.Union[MetaOapg.properties.question_id, schemas.Unset]: ...
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["site"]) -> typing.Union['InboxItemsItemSite', schemas.Unset]: ...
    
    @typing.overload
    def get_item_oapg(self, name: str) -> typing.Union[schemas.UnsetAnyTypeSchema, schemas.Unset]: ...
    
    def get_item_oapg(self, name: typing.Union[typing_extensions.Literal["title", "answer_id", "body", "comment_id", "creation_date", "is_unread", "item_type", "link", "question_id", "site", ], str]):
        return super().get_item_oapg(name)
    

    def __new__(
        cls,
        *args: typing.Union[dict, frozendict.frozendict, ],
        title: typing.Union[MetaOapg.properties.title, str, schemas.Unset] = schemas.unset,
        answer_id: typing.Union[MetaOapg.properties.answer_id, decimal.Decimal, int, schemas.Unset] = schemas.unset,
        body: typing.Union[MetaOapg.properties.body, str, schemas.Unset] = schemas.unset,
        comment_id: typing.Union[MetaOapg.properties.comment_id, decimal.Decimal, int, schemas.Unset] = schemas.unset,
        creation_date: typing.Union[MetaOapg.properties.creation_date, decimal.Decimal, int, schemas.Unset] = schemas.unset,
        is_unread: typing.Union[MetaOapg.properties.is_unread, bool, schemas.Unset] = schemas.unset,
        item_type: typing.Union[MetaOapg.properties.item_type, str, schemas.Unset] = schemas.unset,
        link: typing.Union[MetaOapg.properties.link, str, schemas.Unset] = schemas.unset,
        question_id: typing.Union[MetaOapg.properties.question_id, decimal.Decimal, int, schemas.Unset] = schemas.unset,
        site: typing.Union['InboxItemsItemSite', schemas.Unset] = schemas.unset,
        _configuration: typing.Optional[schemas.Configuration] = None,
        **kwargs: typing.Union[schemas.AnyTypeSchema, dict, frozendict.frozendict, str, date, datetime, uuid.UUID, int, float, decimal.Decimal, None, list, tuple, bytes],
    ) -> 'InboxItemsItem':
        return super().__new__(
            cls,
            *args,
            title=title,
            answer_id=answer_id,
            body=body,
            comment_id=comment_id,
            creation_date=creation_date,
            is_unread=is_unread,
            item_type=item_type,
            link=link,
            question_id=question_id,
            site=site,
            _configuration=_configuration,
            **kwargs,
        )

from stack_exchange_python_sdk.model.inbox_items_item_site import InboxItemsItemSite
