# coding: utf-8

"""
    StackExchange

    Stack Exchange is a network of 130+ Q&A communities including Stack Overflow. 

    The version of the OpenAPI document: 2.0
    Generated by: https://konfigthis.com
"""

from datetime import date, datetime  # noqa: F401
import decimal  # noqa: F401
import functools  # noqa: F401
import io  # noqa: F401
import re  # noqa: F401
import typing  # noqa: F401
import typing_extensions  # noqa: F401
import uuid  # noqa: F401

import frozendict  # noqa: F401

from stack_exchange_python_sdk import schemas  # noqa: F401


class TagWikisItem(
    schemas.DictSchema
):
    """
    This class is auto generated by Konfig (https://konfigthis.com)
    """


    class MetaOapg:
        
        class properties:
            body = schemas.StrSchema
            body_last_edit_date = schemas.IntSchema
            excerpt = schemas.StrSchema
            excerpt_last_edit_date = schemas.IntSchema
        
            @staticmethod
            def last_body_editor() -> typing.Type['TagWikisItemLastBodyEditor']:
                return TagWikisItemLastBodyEditor
        
            @staticmethod
            def last_excerpt_editor() -> typing.Type['TagWikisItemLastExcerptEditor']:
                return TagWikisItemLastExcerptEditor
            tag_name = schemas.StrSchema
            __annotations__ = {
                "body": body,
                "body_last_edit_date": body_last_edit_date,
                "excerpt": excerpt,
                "excerpt_last_edit_date": excerpt_last_edit_date,
                "last_body_editor": last_body_editor,
                "last_excerpt_editor": last_excerpt_editor,
                "tag_name": tag_name,
            }
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["body"]) -> MetaOapg.properties.body: ...
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["body_last_edit_date"]) -> MetaOapg.properties.body_last_edit_date: ...
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["excerpt"]) -> MetaOapg.properties.excerpt: ...
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["excerpt_last_edit_date"]) -> MetaOapg.properties.excerpt_last_edit_date: ...
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["last_body_editor"]) -> 'TagWikisItemLastBodyEditor': ...
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["last_excerpt_editor"]) -> 'TagWikisItemLastExcerptEditor': ...
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["tag_name"]) -> MetaOapg.properties.tag_name: ...
    
    @typing.overload
    def __getitem__(self, name: str) -> schemas.UnsetAnyTypeSchema: ...
    
    def __getitem__(self, name: typing.Union[typing_extensions.Literal["body", "body_last_edit_date", "excerpt", "excerpt_last_edit_date", "last_body_editor", "last_excerpt_editor", "tag_name", ], str]):
        # dict_instance[name] accessor
        return super().__getitem__(name)
    
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["body"]) -> typing.Union[MetaOapg.properties.body, schemas.Unset]: ...
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["body_last_edit_date"]) -> typing.Union[MetaOapg.properties.body_last_edit_date, schemas.Unset]: ...
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["excerpt"]) -> typing.Union[MetaOapg.properties.excerpt, schemas.Unset]: ...
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["excerpt_last_edit_date"]) -> typing.Union[MetaOapg.properties.excerpt_last_edit_date, schemas.Unset]: ...
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["last_body_editor"]) -> typing.Union['TagWikisItemLastBodyEditor', schemas.Unset]: ...
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["last_excerpt_editor"]) -> typing.Union['TagWikisItemLastExcerptEditor', schemas.Unset]: ...
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["tag_name"]) -> typing.Union[MetaOapg.properties.tag_name, schemas.Unset]: ...
    
    @typing.overload
    def get_item_oapg(self, name: str) -> typing.Union[schemas.UnsetAnyTypeSchema, schemas.Unset]: ...
    
    def get_item_oapg(self, name: typing.Union[typing_extensions.Literal["body", "body_last_edit_date", "excerpt", "excerpt_last_edit_date", "last_body_editor", "last_excerpt_editor", "tag_name", ], str]):
        return super().get_item_oapg(name)
    

    def __new__(
        cls,
        *args: typing.Union[dict, frozendict.frozendict, ],
        body: typing.Union[MetaOapg.properties.body, str, schemas.Unset] = schemas.unset,
        body_last_edit_date: typing.Union[MetaOapg.properties.body_last_edit_date, decimal.Decimal, int, schemas.Unset] = schemas.unset,
        excerpt: typing.Union[MetaOapg.properties.excerpt, str, schemas.Unset] = schemas.unset,
        excerpt_last_edit_date: typing.Union[MetaOapg.properties.excerpt_last_edit_date, decimal.Decimal, int, schemas.Unset] = schemas.unset,
        last_body_editor: typing.Union['TagWikisItemLastBodyEditor', schemas.Unset] = schemas.unset,
        last_excerpt_editor: typing.Union['TagWikisItemLastExcerptEditor', schemas.Unset] = schemas.unset,
        tag_name: typing.Union[MetaOapg.properties.tag_name, str, schemas.Unset] = schemas.unset,
        _configuration: typing.Optional[schemas.Configuration] = None,
        **kwargs: typing.Union[schemas.AnyTypeSchema, dict, frozendict.frozendict, str, date, datetime, uuid.UUID, int, float, decimal.Decimal, None, list, tuple, bytes],
    ) -> 'TagWikisItem':
        return super().__new__(
            cls,
            *args,
            body=body,
            body_last_edit_date=body_last_edit_date,
            excerpt=excerpt,
            excerpt_last_edit_date=excerpt_last_edit_date,
            last_body_editor=last_body_editor,
            last_excerpt_editor=last_excerpt_editor,
            tag_name=tag_name,
            _configuration=_configuration,
            **kwargs,
        )

from stack_exchange_python_sdk.model.tag_wikis_item_last_body_editor import TagWikisItemLastBodyEditor
from stack_exchange_python_sdk.model.tag_wikis_item_last_excerpt_editor import TagWikisItemLastExcerptEditor
