# coding: utf-8

"""
    StackExchange

    Stack Exchange is a network of 130+ Q&A communities including Stack Overflow. 

    The version of the OpenAPI document: 2.0
    Generated by: https://konfigthis.com
"""

from datetime import datetime, date
import typing
from enum import Enum
from typing_extensions import TypedDict, Literal, TYPE_CHECKING

from stack_exchange_python_sdk.type.access_tokens_item_scope import AccessTokensItemScope

class RequiredAccessTokensItem(TypedDict):
    pass

class OptionalAccessTokensItem(TypedDict, total=False):
    access_token: str

    account_id: int

    expires_on_date: int

    scope: AccessTokensItemScope

class AccessTokensItem(RequiredAccessTokensItem, OptionalAccessTokensItem):
    pass
