# coding: utf-8

"""
    StackExchange

    Stack Exchange is a network of 130+ Q&A communities including Stack Overflow. 

    The version of the OpenAPI document: 2.0
    Generated by: https://konfigthis.com
"""

from datetime import datetime, date
import typing
from enum import Enum
from typing_extensions import TypedDict, Literal, TYPE_CHECKING


class RequiredAccountMergeItem(TypedDict):
    pass

class OptionalAccountMergeItem(TypedDict, total=False):
    merge_date: int

    new_account_id: int

    old_account_id: int

class AccountMergeItem(RequiredAccountMergeItem, OptionalAccountMergeItem):
    pass
