# coding: utf-8

"""
    StackExchange

    Stack Exchange is a network of 130+ Q&A communities including Stack Overflow. 

    The version of the OpenAPI document: 2.0
    Generated by: https://konfigthis.com
"""

from datetime import datetime, date
import typing
from enum import Enum
from typing_extensions import TypedDict, Literal, TYPE_CHECKING

from stack_exchange_python_sdk.type.answers_item_awarded_bounty_users import AnswersItemAwardedBountyUsers
from stack_exchange_python_sdk.type.answers_item_comments import AnswersItemComments
from stack_exchange_python_sdk.type.answers_item_last_editor import AnswersItemLastEditor
from stack_exchange_python_sdk.type.answers_item_owner import AnswersItemOwner
from stack_exchange_python_sdk.type.answers_item_tags import AnswersItemTags

class RequiredAnswersItem(TypedDict):
    pass

class OptionalAnswersItem(TypedDict, total=False):
    tags: AnswersItemTags

    title: str

    accepted: bool

    answer_id: int

    awarded_bounty_amount: int

    awarded_bounty_users: AnswersItemAwardedBountyUsers

    body: str

    body_markdown: str

    can_flag: bool

    comment_count: int

    comments: AnswersItemComments

    community_owned_date: int

    creation_date: int

    down_vote_count: int

    downvoted: bool

    is_accepted: bool

    last_activity_date: int

    last_edit_date: int

    last_editor: AnswersItemLastEditor

    link: str

    locked_date: int

    owner: AnswersItemOwner

    question_id: int

    score: int

    share_link: str

    up_vote_count: int

    upvoted: bool

class AnswersItem(RequiredAnswersItem, OptionalAnswersItem):
    pass
