# coding: utf-8

"""
    StackExchange

    Stack Exchange is a network of 130+ Q&A communities including Stack Overflow. 

    The version of the OpenAPI document: 2.0
    Generated by: https://konfigthis.com
"""

from datetime import datetime, date
import typing
from enum import Enum
from typing_extensions import TypedDict, Literal, TYPE_CHECKING

from stack_exchange_python_sdk.type.filters_item_included_fields import FiltersItemIncludedFields

class RequiredFiltersItem(TypedDict):
    pass

class OptionalFiltersItem(TypedDict, total=False):
    filter: str

    filter_type: str

    included_fields: FiltersItemIncludedFields

class FiltersItem(RequiredFiltersItem, OptionalFiltersItem):
    pass
