# coding: utf-8

"""
    StackExchange

    Stack Exchange is a network of 130+ Q&A communities including Stack Overflow. 

    The version of the OpenAPI document: 2.0
    Generated by: https://konfigthis.com
"""

from datetime import datetime, date
import typing
from enum import Enum
from typing_extensions import TypedDict, Literal, TYPE_CHECKING

from stack_exchange_python_sdk.type.info_object_site_aliases import InfoObjectSiteAliases
from stack_exchange_python_sdk.type.info_object_site_markdown_extensions import InfoObjectSiteMarkdownExtensions
from stack_exchange_python_sdk.type.info_object_site_related_sites import InfoObjectSiteRelatedSites
from stack_exchange_python_sdk.type.info_object_site_styling import InfoObjectSiteStyling

class RequiredInfoObjectSite(TypedDict):
    pass

class OptionalInfoObjectSite(TypedDict, total=False):
    aliases: InfoObjectSiteAliases

    api_site_parameter: str

    audience: str

    closed_beta_date: int

    favicon_url: str

    high_resolution_icon_url: str

    icon_url: str

    launch_date: int

    logo_url: str

    markdown_extensions: InfoObjectSiteMarkdownExtensions

    name: str

    open_beta_date: int

    related_sites: InfoObjectSiteRelatedSites

    site_state: str

    site_type: str

    site_url: str

    styling: InfoObjectSiteStyling

    twitter_account: str

class InfoObjectSite(RequiredInfoObjectSite, OptionalInfoObjectSite):
    pass
