# coding: utf-8

"""
    StackExchange

    Stack Exchange is a network of 130+ Q&A communities including Stack Overflow. 

    The version of the OpenAPI document: 2.0
    Generated by: https://konfigthis.com
"""

from datetime import datetime, date
import typing
from enum import Enum
from typing_extensions import TypedDict, Literal, TYPE_CHECKING

from stack_exchange_python_sdk.type.network_users_item_badge_counts import NetworkUsersItemBadgeCounts
from stack_exchange_python_sdk.type.network_users_item_top_answers import NetworkUsersItemTopAnswers
from stack_exchange_python_sdk.type.network_users_item_top_questions import NetworkUsersItemTopQuestions

class RequiredNetworkUsersItem(TypedDict):
    pass

class OptionalNetworkUsersItem(TypedDict, total=False):
    account_id: int

    answer_count: int

    badge_counts: NetworkUsersItemBadgeCounts

    creation_date: int

    last_access_date: int

    question_count: int

    reputation: int

    site_name: str

    site_url: str

    top_answers: NetworkUsersItemTopAnswers

    top_questions: NetworkUsersItemTopQuestions

    user_id: int

    user_type: str

class NetworkUsersItem(RequiredNetworkUsersItem, OptionalNetworkUsersItem):
    pass
