# coding: utf-8

"""
    StackExchange

    Stack Exchange is a network of 130+ Q&A communities including Stack Overflow. 

    The version of the OpenAPI document: 2.0
    Generated by: https://konfigthis.com
"""

from datetime import datetime, date
import typing
from enum import Enum
from typing_extensions import TypedDict, Literal, TYPE_CHECKING

from stack_exchange_python_sdk.type.question_timeline_events_item_owner import QuestionTimelineEventsItemOwner
from stack_exchange_python_sdk.type.question_timeline_events_item_user import QuestionTimelineEventsItemUser

class RequiredQuestionTimelineEventsItem(TypedDict):
    pass

class OptionalQuestionTimelineEventsItem(TypedDict, total=False):
    comment_id: int

    creation_date: int

    down_vote_count: int

    owner: QuestionTimelineEventsItemOwner

    post_id: int

    question_id: int

    revision_guid: str

    timeline_type: str

    up_vote_count: int

    user: QuestionTimelineEventsItemUser

class QuestionTimelineEventsItem(RequiredQuestionTimelineEventsItem, OptionalQuestionTimelineEventsItem):
    pass
