# coding: utf-8

"""
    StackExchange

    Stack Exchange is a network of 130+ Q&A communities including Stack Overflow. 

    The version of the OpenAPI document: 2.0
    Generated by: https://konfigthis.com
"""

from datetime import datetime, date
import typing
from enum import Enum
from typing_extensions import TypedDict, Literal, TYPE_CHECKING

from stack_exchange_python_sdk.type.questions_item_closed_details_by_users import QuestionsItemClosedDetailsByUsers
from stack_exchange_python_sdk.type.questions_item_closed_details_original_questions import QuestionsItemClosedDetailsOriginalQuestions

class RequiredQuestionsItemClosedDetails(TypedDict):
    pass

class OptionalQuestionsItemClosedDetails(TypedDict, total=False):
    description: str

    by_users: QuestionsItemClosedDetailsByUsers

    on_hold: bool

    original_questions: QuestionsItemClosedDetailsOriginalQuestions

    reason: str

class QuestionsItemClosedDetails(RequiredQuestionsItemClosedDetails, OptionalQuestionsItemClosedDetails):
    pass
