# coding: utf-8

"""
    StackExchange

    Stack Exchange is a network of 130+ Q&A communities including Stack Overflow. 

    The version of the OpenAPI document: 2.0
    Generated by: https://konfigthis.com
"""

from datetime import datetime, date
import typing
from enum import Enum
from typing_extensions import TypedDict, Literal, TYPE_CHECKING

from stack_exchange_python_sdk.type.questions_item_migrated_to_other_site import QuestionsItemMigratedToOtherSite

class RequiredQuestionsItemMigratedTo(TypedDict):
    pass

class OptionalQuestionsItemMigratedTo(TypedDict, total=False):
    on_date: int

    other_site: QuestionsItemMigratedToOtherSite

    question_id: int

class QuestionsItemMigratedTo(RequiredQuestionsItemMigratedTo, OptionalQuestionsItemMigratedTo):
    pass
