# coding: utf-8

"""
    StackExchange

    Stack Exchange is a network of 130+ Q&A communities including Stack Overflow. 

    The version of the OpenAPI document: 2.0
    Generated by: https://konfigthis.com
"""

from datetime import datetime, date
import typing
from enum import Enum
from typing_extensions import TypedDict, Literal, TYPE_CHECKING


class RequiredReputationChangesItem(TypedDict):
    pass

class OptionalReputationChangesItem(TypedDict, total=False):
    title: str

    link: str

    on_date: int

    post_id: int

    post_type: str

    reputation_change: int

    user_id: int

    vote_type: str

class ReputationChangesItem(RequiredReputationChangesItem, OptionalReputationChangesItem):
    pass
