# coding: utf-8

"""
    StackExchange

    Stack Exchange is a network of 130+ Q&A communities including Stack Overflow. 

    The version of the OpenAPI document: 2.0
    Generated by: https://konfigthis.com
"""

from datetime import datetime, date
import typing
from enum import Enum
from typing_extensions import TypedDict, Literal, TYPE_CHECKING

from stack_exchange_python_sdk.type.revisions_item_last_tags import RevisionsItemLastTags
from stack_exchange_python_sdk.type.revisions_item_tags import RevisionsItemTags
from stack_exchange_python_sdk.type.revisions_item_user import RevisionsItemUser

class RequiredRevisionsItem(TypedDict):
    pass

class OptionalRevisionsItem(TypedDict, total=False):
    tags: RevisionsItemTags

    title: str

    body: str

    comment: str

    creation_date: int

    is_rollback: bool

    last_body: str

    last_tags: RevisionsItemLastTags

    last_title: str

    post_id: int

    post_type: str

    revision_guid: str

    revision_number: int

    revision_type: str

    set_community_wiki: bool

    user: RevisionsItemUser

class RevisionsItem(RequiredRevisionsItem, OptionalRevisionsItem):
    pass
