# coding: utf-8

"""
    StackExchange

    Stack Exchange is a network of 130+ Q&A communities including Stack Overflow. 

    The version of the OpenAPI document: 2.0
    Generated by: https://konfigthis.com
"""

from datetime import datetime, date
import typing
from enum import Enum
from typing_extensions import TypedDict, Literal, TYPE_CHECKING

from stack_exchange_python_sdk.type.single_filter_included_fields import SingleFilterIncludedFields

class RequiredSingleFilter(TypedDict):
    pass

class OptionalSingleFilter(TypedDict, total=False):
    filter: str

    filter_type: str

    included_fields: SingleFilterIncludedFields

class SingleFilter(RequiredSingleFilter, OptionalSingleFilter):
    pass
