# coding: utf-8

"""
    StackExchange

    Stack Exchange is a network of 130+ Q&A communities including Stack Overflow. 

    The version of the OpenAPI document: 2.0
    Generated by: https://konfigthis.com
"""

from datetime import datetime, date
import typing
from enum import Enum
from typing_extensions import TypedDict, Literal, TYPE_CHECKING

from stack_exchange_python_sdk.type.tag_wikis_item_last_body_editor import TagWikisItemLastBodyEditor
from stack_exchange_python_sdk.type.tag_wikis_item_last_excerpt_editor import TagWikisItemLastExcerptEditor

class RequiredTagWikisItem(TypedDict):
    pass

class OptionalTagWikisItem(TypedDict, total=False):
    body: str

    body_last_edit_date: int

    excerpt: str

    excerpt_last_edit_date: int

    last_body_editor: TagWikisItemLastBodyEditor

    last_excerpt_editor: TagWikisItemLastExcerptEditor

    tag_name: str

class TagWikisItem(RequiredTagWikisItem, OptionalTagWikisItem):
    pass
