# coding: utf-8

"""
    StackExchange

    Stack Exchange is a network of 130+ Q&A communities including Stack Overflow. 

    The version of the OpenAPI document: 2.0
    Generated by: https://konfigthis.com
"""

from datetime import datetime, date
import typing
from enum import Enum
from typing_extensions import TypedDict, Literal, TYPE_CHECKING

from stack_exchange_python_sdk.type.tags_item_synonyms import TagsItemSynonyms

class RequiredTagsItem(TypedDict):
    pass

class OptionalTagsItem(TypedDict, total=False):
    count: int

    has_synonyms: bool

    is_moderator_only: bool

    is_required: bool

    last_activity_date: int

    name: str

    synonyms: TagsItemSynonyms

    user_id: int

class TagsItem(RequiredTagsItem, OptionalTagsItem):
    pass
