# coding: utf-8

"""
    StackExchange

    Stack Exchange is a network of 130+ Q&A communities including Stack Overflow. 

    The version of the OpenAPI document: 2.0
    Generated by: https://konfigthis.com
"""

from datetime import datetime, date
import typing
from enum import Enum
from typing_extensions import TypedDict, Literal, TYPE_CHECKING


class RequiredTopTagObjectsItem(TypedDict):
    pass

class OptionalTopTagObjectsItem(TypedDict, total=False):
    answer_count: int

    answer_score: int

    question_count: int

    question_score: int

    tag_name: str

    user_id: int

class TopTagObjectsItem(RequiredTopTagObjectsItem, OptionalTopTagObjectsItem):
    pass
