# coding: utf-8

"""
    StackExchange

    Stack Exchange is a network of 130+ Q&A communities including Stack Overflow. 

    The version of the OpenAPI document: 2.0
    Generated by: https://konfigthis.com
"""

from datetime import datetime, date
import typing
from enum import Enum
from typing_extensions import TypedDict, Literal, TYPE_CHECKING


class RequiredUserTimelineObjectsItem(TypedDict):
    pass

class OptionalUserTimelineObjectsItem(TypedDict, total=False):
    title: str

    badge_id: int

    comment_id: int

    creation_date: int

    detail: str

    link: str

    post_id: int

    post_type: str

    suggested_edit_id: int

    timeline_type: str

    user_id: int

class UserTimelineObjectsItem(RequiredUserTimelineObjectsItem, OptionalUserTimelineObjectsItem):
    pass
