# coding: utf-8

"""
    StackExchange

    Stack Exchange is a network of 130+ Q&A communities including Stack Overflow. 

    The version of the OpenAPI document: 2.0
    Generated by: https://konfigthis.com
"""

from datetime import datetime, date
import typing
from enum import Enum
from typing_extensions import TypedDict, Literal, TYPE_CHECKING
from pydantic import BaseModel, Field, RootModel

from stack_exchange_python_sdk.pydantic.answers_item_awarded_bounty_users import AnswersItemAwardedBountyUsers
from stack_exchange_python_sdk.pydantic.answers_item_comments import AnswersItemComments
from stack_exchange_python_sdk.pydantic.answers_item_last_editor import AnswersItemLastEditor
from stack_exchange_python_sdk.pydantic.answers_item_owner import AnswersItemOwner
from stack_exchange_python_sdk.pydantic.answers_item_tags import AnswersItemTags

class AnswersItem(BaseModel):
    tags: typing.Optional[AnswersItemTags] = Field(None, alias='tags')

    title: typing.Optional[str] = Field(None, alias='title')

    accepted: typing.Optional[bool] = Field(None, alias='accepted')

    answer_id: typing.Optional[int] = Field(None, alias='answer_id')

    awarded_bounty_amount: typing.Optional[int] = Field(None, alias='awarded_bounty_amount')

    awarded_bounty_users: typing.Optional[AnswersItemAwardedBountyUsers] = Field(None, alias='awarded_bounty_users')

    body: typing.Optional[str] = Field(None, alias='body')

    body_markdown: typing.Optional[str] = Field(None, alias='body_markdown')

    can_flag: typing.Optional[bool] = Field(None, alias='can_flag')

    comment_count: typing.Optional[int] = Field(None, alias='comment_count')

    comments: typing.Optional[AnswersItemComments] = Field(None, alias='comments')

    community_owned_date: typing.Optional[int] = Field(None, alias='community_owned_date')

    creation_date: typing.Optional[int] = Field(None, alias='creation_date')

    down_vote_count: typing.Optional[int] = Field(None, alias='down_vote_count')

    downvoted: typing.Optional[bool] = Field(None, alias='downvoted')

    is_accepted: typing.Optional[bool] = Field(None, alias='is_accepted')

    last_activity_date: typing.Optional[int] = Field(None, alias='last_activity_date')

    last_edit_date: typing.Optional[int] = Field(None, alias='last_edit_date')

    last_editor: typing.Optional[AnswersItemLastEditor] = Field(None, alias='last_editor')

    link: typing.Optional[str] = Field(None, alias='link')

    locked_date: typing.Optional[int] = Field(None, alias='locked_date')

    owner: typing.Optional[AnswersItemOwner] = Field(None, alias='owner')

    question_id: typing.Optional[int] = Field(None, alias='question_id')

    score: typing.Optional[int] = Field(None, alias='score')

    share_link: typing.Optional[str] = Field(None, alias='share_link')

    up_vote_count: typing.Optional[int] = Field(None, alias='up_vote_count')

    upvoted: typing.Optional[bool] = Field(None, alias='upvoted')
    class Config:
        arbitrary_types_allowed = True
