# coding: utf-8

"""
    StackExchange

    Stack Exchange is a network of 130+ Q&A communities including Stack Overflow. 

    The version of the OpenAPI document: 2.0
    Generated by: https://konfigthis.com
"""

from datetime import datetime, date
import typing
from enum import Enum
from typing_extensions import TypedDict, Literal, TYPE_CHECKING
from pydantic import BaseModel, Field, RootModel

from stack_exchange_python_sdk.pydantic.badges_item_user import BadgesItemUser

class BadgesItem(BaseModel):
    description: typing.Optional[str] = Field(None, alias='description')

    award_count: typing.Optional[int] = Field(None, alias='award_count')

    badge_id: typing.Optional[int] = Field(None, alias='badge_id')

    badge_type: typing.Optional[str] = Field(None, alias='badge_type')

    link: typing.Optional[str] = Field(None, alias='link')

    name: typing.Optional[str] = Field(None, alias='name')

    rank: typing.Optional[str] = Field(None, alias='rank')

    user: typing.Optional[BadgesItemUser] = Field(None, alias='user')
    class Config:
        arbitrary_types_allowed = True
