# coding: utf-8

"""
    StackExchange

    Stack Exchange is a network of 130+ Q&A communities including Stack Overflow. 

    The version of the OpenAPI document: 2.0
    Generated by: https://konfigthis.com
"""

from datetime import datetime, date
import typing
from enum import Enum
from typing_extensions import TypedDict, Literal, TYPE_CHECKING
from pydantic import BaseModel, Field, RootModel

from stack_exchange_python_sdk.pydantic.inbox_items_item_site import InboxItemsItemSite

class InboxItemsItem(BaseModel):
    title: typing.Optional[str] = Field(None, alias='title')

    answer_id: typing.Optional[int] = Field(None, alias='answer_id')

    body: typing.Optional[str] = Field(None, alias='body')

    comment_id: typing.Optional[int] = Field(None, alias='comment_id')

    creation_date: typing.Optional[int] = Field(None, alias='creation_date')

    is_unread: typing.Optional[bool] = Field(None, alias='is_unread')

    item_type: typing.Optional[str] = Field(None, alias='item_type')

    link: typing.Optional[str] = Field(None, alias='link')

    question_id: typing.Optional[int] = Field(None, alias='question_id')

    site: typing.Optional[InboxItemsItemSite] = Field(None, alias='site')
    class Config:
        arbitrary_types_allowed = True
