# coding: utf-8

"""
    StackExchange

    Stack Exchange is a network of 130+ Q&A communities including Stack Overflow. 

    The version of the OpenAPI document: 2.0
    Generated by: https://konfigthis.com
"""

from datetime import datetime, date
import typing
from enum import Enum
from typing_extensions import TypedDict, Literal, TYPE_CHECKING
from pydantic import BaseModel, Field, RootModel

from stack_exchange_python_sdk.pydantic.network_users_item_badge_counts import NetworkUsersItemBadgeCounts
from stack_exchange_python_sdk.pydantic.network_users_item_top_answers import NetworkUsersItemTopAnswers
from stack_exchange_python_sdk.pydantic.network_users_item_top_questions import NetworkUsersItemTopQuestions

class NetworkUsersItem(BaseModel):
    account_id: typing.Optional[int] = Field(None, alias='account_id')

    answer_count: typing.Optional[int] = Field(None, alias='answer_count')

    badge_counts: typing.Optional[NetworkUsersItemBadgeCounts] = Field(None, alias='badge_counts')

    creation_date: typing.Optional[int] = Field(None, alias='creation_date')

    last_access_date: typing.Optional[int] = Field(None, alias='last_access_date')

    question_count: typing.Optional[int] = Field(None, alias='question_count')

    reputation: typing.Optional[int] = Field(None, alias='reputation')

    site_name: typing.Optional[str] = Field(None, alias='site_name')

    site_url: typing.Optional[str] = Field(None, alias='site_url')

    top_answers: typing.Optional[NetworkUsersItemTopAnswers] = Field(None, alias='top_answers')

    top_questions: typing.Optional[NetworkUsersItemTopQuestions] = Field(None, alias='top_questions')

    user_id: typing.Optional[int] = Field(None, alias='user_id')

    user_type: typing.Optional[str] = Field(None, alias='user_type')
    class Config:
        arbitrary_types_allowed = True
