# coding: utf-8

"""
    StackExchange

    Stack Exchange is a network of 130+ Q&A communities including Stack Overflow. 

    The version of the OpenAPI document: 2.0
    Generated by: https://konfigthis.com
"""

from datetime import datetime, date
import typing
from enum import Enum
from typing_extensions import TypedDict, Literal, TYPE_CHECKING
from pydantic import BaseModel, Field, RootModel

from stack_exchange_python_sdk.pydantic.questions_item_closed_details_by_users import QuestionsItemClosedDetailsByUsers
from stack_exchange_python_sdk.pydantic.questions_item_closed_details_original_questions import QuestionsItemClosedDetailsOriginalQuestions

class QuestionsItemClosedDetails(BaseModel):
    description: typing.Optional[str] = Field(None, alias='description')

    by_users: typing.Optional[QuestionsItemClosedDetailsByUsers] = Field(None, alias='by_users')

    on_hold: typing.Optional[bool] = Field(None, alias='on_hold')

    original_questions: typing.Optional[QuestionsItemClosedDetailsOriginalQuestions] = Field(None, alias='original_questions')

    reason: typing.Optional[str] = Field(None, alias='reason')
    class Config:
        arbitrary_types_allowed = True
