# coding: utf-8

"""
    StackExchange

    Stack Exchange is a network of 130+ Q&A communities including Stack Overflow. 

    The version of the OpenAPI document: 2.0
    Generated by: https://konfigthis.com
"""

from datetime import datetime, date
import typing
from enum import Enum
from typing_extensions import TypedDict, Literal, TYPE_CHECKING
from pydantic import BaseModel, Field, RootModel


class ReputationObjectsItem(BaseModel):
    title: typing.Optional[str] = Field(None, alias='title')

    link: typing.Optional[str] = Field(None, alias='link')

    on_date: typing.Optional[int] = Field(None, alias='on_date')

    post_id: typing.Optional[int] = Field(None, alias='post_id')

    post_type: typing.Optional[str] = Field(None, alias='post_type')

    reputation_change: typing.Optional[int] = Field(None, alias='reputation_change')

    user_id: typing.Optional[int] = Field(None, alias='user_id')

    vote_type: typing.Optional[str] = Field(None, alias='vote_type')
    class Config:
        arbitrary_types_allowed = True
