# coding: utf-8

"""
    StackExchange

    Stack Exchange is a network of 130+ Q&A communities including Stack Overflow. 

    The version of the OpenAPI document: 2.0
    Generated by: https://konfigthis.com
"""

from datetime import datetime, date
import typing
from enum import Enum
from typing_extensions import TypedDict, Literal, TYPE_CHECKING
from pydantic import BaseModel, Field, RootModel

from stack_exchange_python_sdk.pydantic.revisions_item_last_tags import RevisionsItemLastTags
from stack_exchange_python_sdk.pydantic.revisions_item_tags import RevisionsItemTags
from stack_exchange_python_sdk.pydantic.revisions_item_user import RevisionsItemUser

class RevisionsItem(BaseModel):
    tags: typing.Optional[RevisionsItemTags] = Field(None, alias='tags')

    title: typing.Optional[str] = Field(None, alias='title')

    body: typing.Optional[str] = Field(None, alias='body')

    comment: typing.Optional[str] = Field(None, alias='comment')

    creation_date: typing.Optional[int] = Field(None, alias='creation_date')

    is_rollback: typing.Optional[bool] = Field(None, alias='is_rollback')

    last_body: typing.Optional[str] = Field(None, alias='last_body')

    last_tags: typing.Optional[RevisionsItemLastTags] = Field(None, alias='last_tags')

    last_title: typing.Optional[str] = Field(None, alias='last_title')

    post_id: typing.Optional[int] = Field(None, alias='post_id')

    post_type: typing.Optional[str] = Field(None, alias='post_type')

    revision_guid: typing.Optional[str] = Field(None, alias='revision_guid')

    revision_number: typing.Optional[int] = Field(None, alias='revision_number')

    revision_type: typing.Optional[str] = Field(None, alias='revision_type')

    set_community_wiki: typing.Optional[bool] = Field(None, alias='set_community_wiki')

    user: typing.Optional[RevisionsItemUser] = Field(None, alias='user')
    class Config:
        arbitrary_types_allowed = True
