# coding: utf-8

"""
    StackExchange

    Stack Exchange is a network of 130+ Q&A communities including Stack Overflow. 

    The version of the OpenAPI document: 2.0
    Generated by: https://konfigthis.com
"""

from datetime import datetime, date
import typing
from enum import Enum
from typing_extensions import TypedDict, Literal, TYPE_CHECKING
from pydantic import BaseModel, Field, RootModel


class TagSynonymsItem(BaseModel):
    applied_count: typing.Optional[int] = Field(None, alias='applied_count')

    creation_date: typing.Optional[int] = Field(None, alias='creation_date')

    from_tag: typing.Optional[str] = Field(None, alias='from_tag')

    last_applied_date: typing.Optional[int] = Field(None, alias='last_applied_date')

    to_tag: typing.Optional[str] = Field(None, alias='to_tag')
    class Config:
        arbitrary_types_allowed = True
