# coding: utf-8

"""
    StackExchange

    Stack Exchange is a network of 130+ Q&A communities including Stack Overflow. 

    The version of the OpenAPI document: 2.0
    Generated by: https://konfigthis.com
"""

from datetime import datetime, date
import typing
from enum import Enum
from typing_extensions import TypedDict, Literal, TYPE_CHECKING
from pydantic import BaseModel, Field, RootModel

from stack_exchange_python_sdk.pydantic.users_item_badge_counts import UsersItemBadgeCounts

class UsersItem(BaseModel):
    about_me: typing.Optional[str] = Field(None, alias='about_me')

    accept_rate: typing.Optional[int] = Field(None, alias='accept_rate')

    account_id: typing.Optional[int] = Field(None, alias='account_id')

    age: typing.Optional[int] = Field(None, alias='age')

    answer_count: typing.Optional[int] = Field(None, alias='answer_count')

    badge_counts: typing.Optional[UsersItemBadgeCounts] = Field(None, alias='badge_counts')

    creation_date: typing.Optional[int] = Field(None, alias='creation_date')

    display_name: typing.Optional[str] = Field(None, alias='display_name')

    down_vote_count: typing.Optional[int] = Field(None, alias='down_vote_count')

    is_employee: typing.Optional[bool] = Field(None, alias='is_employee')

    last_access_date: typing.Optional[int] = Field(None, alias='last_access_date')

    last_modified_date: typing.Optional[int] = Field(None, alias='last_modified_date')

    link: typing.Optional[str] = Field(None, alias='link')

    location: typing.Optional[str] = Field(None, alias='location')

    profile_image: typing.Optional[str] = Field(None, alias='profile_image')

    question_count: typing.Optional[int] = Field(None, alias='question_count')

    reputation: typing.Optional[int] = Field(None, alias='reputation')

    reputation_change_day: typing.Optional[int] = Field(None, alias='reputation_change_day')

    reputation_change_month: typing.Optional[int] = Field(None, alias='reputation_change_month')

    reputation_change_quarter: typing.Optional[int] = Field(None, alias='reputation_change_quarter')

    reputation_change_week: typing.Optional[int] = Field(None, alias='reputation_change_week')

    reputation_change_year: typing.Optional[int] = Field(None, alias='reputation_change_year')

    timed_penalty_date: typing.Optional[int] = Field(None, alias='timed_penalty_date')

    up_vote_count: typing.Optional[int] = Field(None, alias='up_vote_count')

    user_id: typing.Optional[int] = Field(None, alias='user_id')

    user_type: typing.Optional[str] = Field(None, alias='user_type')

    view_count: typing.Optional[int] = Field(None, alias='view_count')

    website_url: typing.Optional[str] = Field(None, alias='website_url')
    class Config:
        arbitrary_types_allowed = True
