# coding: utf-8

"""
    StackExchange

    Stack Exchange is a network of 130+ Q&A communities including Stack Overflow. 

    The version of the OpenAPI document: 2.0
    Generated by: https://konfigthis.com
"""

from datetime import datetime, date
import typing
from enum import Enum
from typing_extensions import TypedDict, Literal, TYPE_CHECKING
from pydantic import BaseModel, Field, RootModel


class UserTimelineObjectsItem(BaseModel):
    title: typing.Optional[str] = Field(None, alias='title')

    badge_id: typing.Optional[int] = Field(None, alias='badge_id')

    comment_id: typing.Optional[int] = Field(None, alias='comment_id')

    creation_date: typing.Optional[int] = Field(None, alias='creation_date')

    detail: typing.Optional[str] = Field(None, alias='detail')

    link: typing.Optional[str] = Field(None, alias='link')

    post_id: typing.Optional[int] = Field(None, alias='post_id')

    post_type: typing.Optional[str] = Field(None, alias='post_type')

    suggested_edit_id: typing.Optional[int] = Field(None, alias='suggested_edit_id')

    timeline_type: typing.Optional[str] = Field(None, alias='timeline_type')

    user_id: typing.Optional[int] = Field(None, alias='user_id')
    class Config:
        arbitrary_types_allowed = True
