# coding: utf-8

"""
    StackExchange

    Stack Exchange is a network of 130+ Q&A communities including Stack Overflow. 

    The version of the OpenAPI document: 2.0
    Generated by: https://konfigthis.com
"""

import unittest

import stack_exchange_python_sdk
from stack_exchange_python_sdk.model.created_comment_reply_to_user_badge_counts import CreatedCommentReplyToUserBadgeCounts
from stack_exchange_python_sdk import configuration


class TestCreatedCommentReplyToUserBadgeCounts(unittest.TestCase):
    """CreatedCommentReplyToUserBadgeCounts unit test stubs"""
    pass


if __name__ == '__main__':
    unittest.main()
