# coding: utf-8

"""
    StackExchange

    Stack Exchange is a network of 130+ Q&A communities including Stack Overflow. 

    The version of the OpenAPI document: 2.0
    Generated by: https://konfigthis.com
"""

import unittest

import stack_exchange_python_sdk
from stack_exchange_python_sdk.model.user_timeline_objects_item import UserTimelineObjectsItem
from stack_exchange_python_sdk import configuration


class TestUserTimelineObjectsItem(unittest.TestCase):
    """UserTimelineObjectsItem unit test stubs"""
    pass


if __name__ == '__main__':
    unittest.main()
