# coding: utf-8

"""
    StackExchange

    Stack Exchange is a network of 130+ Q&A communities including Stack Overflow. 

    The version of the OpenAPI document: 2.0
    Generated by: https://konfigthis.com
"""

from stack_exchange_python_sdk.paths.apps_access_tokens_de_authenticate.get import DeauthenticateList
from stack_exchange_python_sdk.paths.access_tokens_access_tokens_invalidate.get import InvalidateList
from stack_exchange_python_sdk.paths.access_tokens_access_tokens.get import ListPropertiesForMultipleTokens
from stack_exchange_python_sdk.apis.tags.access_token_api_raw import AccessTokenApiRaw


class AccessTokenApi(
    DeauthenticateList,
    InvalidateList,
    ListPropertiesForMultipleTokens,
):
    """NOTE:
    This class is auto generated by Konfig (https://konfigthis.com)
    """
    raw: AccessTokenApiRaw

    def __init__(self, api_client=None):
        super().__init__(api_client)
        self.raw = AccessTokenApiRaw(api_client)
