# coding: utf-8

"""
    StackExchange

    Stack Exchange is a network of 130+ Q&A communities including Stack Overflow. 

    The version of the OpenAPI document: 2.0
    Generated by: https://konfigthis.com
"""

from stack_exchange_python_sdk.paths.answers_ids_comments.get import GetCommentsByIds
from stack_exchange_python_sdk.paths.answers.get import GetList
from stack_exchange_python_sdk.paths.answers_ids.get import GetListByIds
from stack_exchange_python_sdk.paths.questions_ids_answers.get import GetListByQuestionIds
from stack_exchange_python_sdk.paths.questions_unanswered.get import GetListOfUnansweredQuestions
from stack_exchange_python_sdk.paths.me_answers.get import GetUserAnswersList
from stack_exchange_python_sdk.paths.me_tags_tags_top_answers.get import GetUserTopAnswers
from stack_exchange_python_sdk.paths.me_top_answer_tags.get import GetUserTopTags
from stack_exchange_python_sdk.paths.me_questions_no_answers.get import ListNoAnswerQuestions
from stack_exchange_python_sdk.paths.questions_no_answers.get import ListNoAnswerQuestions0
from stack_exchange_python_sdk.paths.tags_tag_top_answerers_period.get import TagTopAnswerers
from stack_exchange_python_sdk.paths.me_questions_unanswered.get import UserUnansweredQuestionsGet
from stack_exchange_python_sdk.apis.tags.answer_api_raw import AnswerApiRaw


class AnswerApi(
    GetCommentsByIds,
    GetList,
    GetListByIds,
    GetListByQuestionIds,
    GetListOfUnansweredQuestions,
    GetUserAnswersList,
    GetUserTopAnswers,
    GetUserTopTags,
    ListNoAnswerQuestions,
    ListNoAnswerQuestions0,
    TagTopAnswerers,
    UserUnansweredQuestionsGet,
):
    """NOTE:
    This class is auto generated by Konfig (https://konfigthis.com)
    """
    raw: AnswerApiRaw

    def __init__(self, api_client=None):
        super().__init__(api_client)
        self.raw = AnswerApiRaw(api_client)
