# coding: utf-8

"""
    StackExchange

    Stack Exchange is a network of 130+ Q&A communities including Stack Overflow. 

    The version of the OpenAPI document: 2.0
    Generated by: https://konfigthis.com
"""

from stack_exchange_python_sdk.paths.answers_ids_comments.get import GetCommentsByIdsRaw
from stack_exchange_python_sdk.paths.answers.get import GetListRaw
from stack_exchange_python_sdk.paths.answers_ids.get import GetListByIdsRaw
from stack_exchange_python_sdk.paths.questions_ids_answers.get import GetListByQuestionIdsRaw
from stack_exchange_python_sdk.paths.questions_unanswered.get import GetListOfUnansweredQuestionsRaw
from stack_exchange_python_sdk.paths.me_answers.get import GetUserAnswersListRaw
from stack_exchange_python_sdk.paths.me_tags_tags_top_answers.get import GetUserTopAnswersRaw
from stack_exchange_python_sdk.paths.me_top_answer_tags.get import GetUserTopTagsRaw
from stack_exchange_python_sdk.paths.me_questions_no_answers.get import ListNoAnswerQuestionsRaw
from stack_exchange_python_sdk.paths.questions_no_answers.get import ListNoAnswerQuestions0Raw
from stack_exchange_python_sdk.paths.tags_tag_top_answerers_period.get import TagTopAnswerersRaw
from stack_exchange_python_sdk.paths.me_questions_unanswered.get import UserUnansweredQuestionsGetRaw


class AnswerApiRaw(
    GetCommentsByIdsRaw,
    GetListRaw,
    GetListByIdsRaw,
    GetListByQuestionIdsRaw,
    GetListOfUnansweredQuestionsRaw,
    GetUserAnswersListRaw,
    GetUserTopAnswersRaw,
    GetUserTopTagsRaw,
    ListNoAnswerQuestionsRaw,
    ListNoAnswerQuestions0Raw,
    TagTopAnswerersRaw,
    UserUnansweredQuestionsGetRaw,
):
    """NOTE:
    This class is auto generated by Konfig (https://konfigthis.com)
    """
    pass
