# coding: utf-8

"""
    StackExchange

    Stack Exchange is a network of 130+ Q&A communities including Stack Overflow. 

    The version of the OpenAPI document: 2.0
    Generated by: https://konfigthis.com
"""

from stack_exchange_python_sdk.paths.badges_name.get import GetAllNamedBadges
from stack_exchange_python_sdk.paths.badges_ids.get import GetBadgesByIds
from stack_exchange_python_sdk.paths.badges_recipients.get import GetRecentAwardedBadges
from stack_exchange_python_sdk.paths.badges_ids_recipients.get import GetRecentAwardedRecipients
from stack_exchange_python_sdk.paths.me_badges.get import GetUserBadges
from stack_exchange_python_sdk.paths.badges.get import ListBadges
from stack_exchange_python_sdk.paths.badges_tags.get import ListTagsBadges
from stack_exchange_python_sdk.apis.tags.badge_api_raw import BadgeApiRaw


class BadgeApi(
    GetAllNamedBadges,
    GetBadgesByIds,
    GetRecentAwardedBadges,
    GetRecentAwardedRecipients,
    GetUserBadges,
    ListBadges,
    ListTagsBadges,
):
    """NOTE:
    This class is auto generated by Konfig (https://konfigthis.com)
    """
    raw: BadgeApiRaw

    def __init__(self, api_client=None):
        super().__init__(api_client)
        self.raw = BadgeApiRaw(api_client)
