# coding: utf-8

"""
    StackExchange

    Stack Exchange is a network of 130+ Q&A communities including Stack Overflow. 

    The version of the OpenAPI document: 2.0
    Generated by: https://konfigthis.com
"""

from stack_exchange_python_sdk.paths.badges_name.get import GetAllNamedBadgesRaw
from stack_exchange_python_sdk.paths.badges_ids.get import GetBadgesByIdsRaw
from stack_exchange_python_sdk.paths.badges_recipients.get import GetRecentAwardedBadgesRaw
from stack_exchange_python_sdk.paths.badges_ids_recipients.get import GetRecentAwardedRecipientsRaw
from stack_exchange_python_sdk.paths.me_badges.get import GetUserBadgesRaw
from stack_exchange_python_sdk.paths.badges.get import ListBadgesRaw
from stack_exchange_python_sdk.paths.badges_tags.get import ListTagsBadgesRaw


class BadgeApiRaw(
    GetAllNamedBadgesRaw,
    GetBadgesByIdsRaw,
    GetRecentAwardedBadgesRaw,
    GetRecentAwardedRecipientsRaw,
    GetUserBadgesRaw,
    ListBadgesRaw,
    ListTagsBadgesRaw,
):
    """NOTE:
    This class is auto generated by Konfig (https://konfigthis.com)
    """
    pass
