# coding: utf-8

"""
    StackExchange

    Stack Exchange is a network of 130+ Q&A communities including Stack Overflow. 

    The version of the OpenAPI document: 2.0
    Generated by: https://konfigthis.com
"""

from stack_exchange_python_sdk.paths.comments_id_delete.post import DeleteAction
from stack_exchange_python_sdk.paths.comments_id_edit.post import EditExisting
from stack_exchange_python_sdk.paths.comments_ids.get import GetCommentsByIds
from stack_exchange_python_sdk.paths.questions_ids_comments.get import GetCommentsList
from stack_exchange_python_sdk.paths.me_comments_to_id.get import GetReplyList
from stack_exchange_python_sdk.paths.comments.get import ListComments
from stack_exchange_python_sdk.paths.me_comments.get import ListOwnedComments
from stack_exchange_python_sdk.apis.tags.comment_api_raw import CommentApiRaw


class CommentApi(
    DeleteAction,
    EditExisting,
    GetCommentsByIds,
    GetCommentsList,
    GetReplyList,
    ListComments,
    ListOwnedComments,
):
    """NOTE:
    This class is auto generated by Konfig (https://konfigthis.com)
    """
    raw: CommentApiRaw

    def __init__(self, api_client=None):
        super().__init__(api_client)
        self.raw = CommentApiRaw(api_client)
