# coding: utf-8

"""
    StackExchange

    Stack Exchange is a network of 130+ Q&A communities including Stack Overflow. 

    The version of the OpenAPI document: 2.0
    Generated by: https://konfigthis.com
"""

from stack_exchange_python_sdk.paths.comments_id_delete.post import DeleteActionRaw
from stack_exchange_python_sdk.paths.comments_id_edit.post import EditExistingRaw
from stack_exchange_python_sdk.paths.comments_ids.get import GetCommentsByIdsRaw
from stack_exchange_python_sdk.paths.questions_ids_comments.get import GetCommentsListRaw
from stack_exchange_python_sdk.paths.me_comments_to_id.get import GetReplyListRaw
from stack_exchange_python_sdk.paths.comments.get import ListCommentsRaw
from stack_exchange_python_sdk.paths.me_comments.get import ListOwnedCommentsRaw


class CommentApiRaw(
    DeleteActionRaw,
    EditExistingRaw,
    GetCommentsByIdsRaw,
    GetCommentsListRaw,
    GetReplyListRaw,
    ListCommentsRaw,
    ListOwnedCommentsRaw,
):
    """NOTE:
    This class is auto generated by Konfig (https://konfigthis.com)
    """
    pass
