# coding: utf-8

"""
    StackExchange

    Stack Exchange is a network of 130+ Q&A communities including Stack Overflow. 

    The version of the OpenAPI document: 2.0
    Generated by: https://konfigthis.com
"""

from stack_exchange_python_sdk.paths.me_suggested_edits.get import GetUserSuggestedEditsRaw
from stack_exchange_python_sdk.paths.suggested_edits.get import ListSuggestedEditsRaw
from stack_exchange_python_sdk.paths.suggested_edits_ids.get import ListSuggestedEdits0Raw


class EditApiRaw(
    GetUserSuggestedEditsRaw,
    ListSuggestedEditsRaw,
    ListSuggestedEdits0Raw,
):
    """NOTE:
    This class is auto generated by Konfig (https://konfigthis.com)
    """
    pass
