# coding: utf-8

"""
    StackExchange

    Stack Exchange is a network of 130+ Q&A communities including Stack Overflow. 

    The version of the OpenAPI document: 2.0
    Generated by: https://konfigthis.com
"""

from stack_exchange_python_sdk.paths.me_favorites.get import GetUserFavorites
from stack_exchange_python_sdk.apis.tags.favorite_api_raw import FavoriteApiRaw


class FavoriteApi(
    GetUserFavorites,
):
    """NOTE:
    This class is auto generated by Konfig (https://konfigthis.com)
    """
    raw: FavoriteApiRaw

    def __init__(self, api_client=None):
        super().__init__(api_client)
        self.raw = FavoriteApiRaw(api_client)
