# coding: utf-8

"""
    StackExchange

    Stack Exchange is a network of 130+ Q&A communities including Stack Overflow. 

    The version of the OpenAPI document: 2.0
    Generated by: https://konfigthis.com
"""

from stack_exchange_python_sdk.paths.filters_create.get import CreateFilter
from stack_exchange_python_sdk.paths.filters_filters.get import GetFilterDetailsByIds
from stack_exchange_python_sdk.apis.tags.filter_api_raw import FilterApiRaw


class FilterApi(
    CreateFilter,
    GetFilterDetailsByIds,
):
    """NOTE:
    This class is auto generated by Konfig (https://konfigthis.com)
    """
    raw: FilterApiRaw

    def __init__(self, api_client=None):
        super().__init__(api_client)
        self.raw = FilterApiRaw(api_client)
