# coding: utf-8

"""
    StackExchange

    Stack Exchange is a network of 130+ Q&A communities including Stack Overflow. 

    The version of the OpenAPI document: 2.0
    Generated by: https://konfigthis.com
"""

from stack_exchange_python_sdk.paths.filters_create.get import CreateFilterRaw
from stack_exchange_python_sdk.paths.filters_filters.get import GetFilterDetailsByIdsRaw


class FilterApiRaw(
    CreateFilterRaw,
    GetFilterDetailsByIdsRaw,
):
    """NOTE:
    This class is auto generated by Konfig (https://konfigthis.com)
    """
    pass
