# coding: utf-8

"""
    StackExchange

    Stack Exchange is a network of 130+ Q&A communities including Stack Overflow. 

    The version of the OpenAPI document: 2.0
    Generated by: https://konfigthis.com
"""

from stack_exchange_python_sdk.paths.info.get import GetStatisticsRaw
from stack_exchange_python_sdk.paths.tags.get import GetTagsListRaw


class InformationApiRaw(
    GetStatisticsRaw,
    GetTagsListRaw,
):
    """NOTE:
    This class is auto generated by Konfig (https://konfigthis.com)
    """
    pass
