# coding: utf-8

"""
    StackExchange

    Stack Exchange is a network of 130+ Q&A communities including Stack Overflow. 

    The version of the OpenAPI document: 2.0
    Generated by: https://konfigthis.com
"""

from stack_exchange_python_sdk.paths.me_inbox_unread.get import GetUnreadItemsInInboxRaw
from stack_exchange_python_sdk.paths.me_notifications_unread.get import GetUnreadItemsInInbox0Raw
from stack_exchange_python_sdk.paths.notifications.get import GetUserNotificationsRaw
from stack_exchange_python_sdk.paths.me_notifications.get import GetUserNotificationsListRaw
from stack_exchange_python_sdk.paths.notifications_unread.get import GetUserUnreadNotificationsRaw


class NotificationApiRaw(
    GetUnreadItemsInInboxRaw,
    GetUnreadItemsInInbox0Raw,
    GetUserNotificationsRaw,
    GetUserNotificationsListRaw,
    GetUserUnreadNotificationsRaw,
):
    """NOTE:
    This class is auto generated by Konfig (https://konfigthis.com)
    """
    pass
