# coding: utf-8

"""
    StackExchange

    Stack Exchange is a network of 130+ Q&A communities including Stack Overflow. 

    The version of the OpenAPI document: 2.0
    Generated by: https://konfigthis.com
"""

from stack_exchange_python_sdk.paths.me_inbox_unread.get import GetUnreadItemsInInbox
from stack_exchange_python_sdk.paths.me_notifications_unread.get import GetUnreadItemsInInbox0
from stack_exchange_python_sdk.paths.notifications.get import GetUserNotifications
from stack_exchange_python_sdk.paths.me_notifications.get import GetUserNotificationsList
from stack_exchange_python_sdk.paths.notifications_unread.get import GetUserUnreadNotifications
from stack_exchange_python_sdk.apis.tags.notification_api_raw import NotificationApiRaw


class NotificationApi(
    GetUnreadItemsInInbox,
    GetUnreadItemsInInbox0,
    GetUserNotifications,
    GetUserNotificationsList,
    GetUserUnreadNotifications,
):
    """NOTE:
    This class is auto generated by Konfig (https://konfigthis.com)
    """
    raw: NotificationApiRaw

    def __init__(self, api_client=None):
        super().__init__(api_client)
        self.raw = NotificationApiRaw(api_client)
