# coding: utf-8

"""
    StackExchange

    Stack Exchange is a network of 130+ Q&A communities including Stack Overflow. 

    The version of the OpenAPI document: 2.0
    Generated by: https://konfigthis.com
"""

from stack_exchange_python_sdk.paths.similar.get import SimilarQuestionsSearchRaw
from stack_exchange_python_sdk.paths.search.get import SiteQuestionsSearchRaw


class QueryApiRaw(
    SimilarQuestionsSearchRaw,
    SiteQuestionsSearchRaw,
):
    """NOTE:
    This class is auto generated by Konfig (https://konfigthis.com)
    """
    pass
