# coding: utf-8

"""
    StackExchange

    Stack Exchange is a network of 130+ Q&A communities including Stack Overflow. 

    The version of the OpenAPI document: 2.0
    Generated by: https://konfigthis.com
"""

from stack_exchange_python_sdk.paths.similar.get import SimilarQuestionsSearch
from stack_exchange_python_sdk.paths.search.get import SiteQuestionsSearch
from stack_exchange_python_sdk.apis.tags.query_api_raw import QueryApiRaw


class QueryApi(
    SimilarQuestionsSearch,
    SiteQuestionsSearch,
):
    """NOTE:
    This class is auto generated by Konfig (https://konfigthis.com)
    """
    raw: QueryApiRaw

    def __init__(self, api_client=None):
        super().__init__(api_client)
        self.raw = QueryApiRaw(api_client)
