# coding: utf-8

"""
    StackExchange

    Stack Exchange is a network of 130+ Q&A communities including Stack Overflow. 

    The version of the OpenAPI document: 2.0
    Generated by: https://konfigthis.com
"""

from stack_exchange_python_sdk.paths.questions.get import GetAllQuestionsRaw
from stack_exchange_python_sdk.paths.questions_ids.get import GetByIdsRaw
from stack_exchange_python_sdk.paths.questions_ids_linked.get import GetLinkedQuestionsRaw
from stack_exchange_python_sdk.paths.questions_ids_timeline.get import GetTimelineEventsRaw
from stack_exchange_python_sdk.paths.me_questions_unaccepted.get import GetUnacceptedListRaw
from stack_exchange_python_sdk.paths.me_questions_featured.get import GetUserFeaturedRaw
from stack_exchange_python_sdk.paths.me_questions.get import GetUserQuestionsListRaw
from stack_exchange_python_sdk.paths.questions_featured.get import ListFeaturedQuestionsRaw
from stack_exchange_python_sdk.paths.questions_ids_related.get import ListRelatedQuestionsRaw


class QuestionApiRaw(
    GetAllQuestionsRaw,
    GetByIdsRaw,
    GetLinkedQuestionsRaw,
    GetTimelineEventsRaw,
    GetUnacceptedListRaw,
    GetUserFeaturedRaw,
    GetUserQuestionsListRaw,
    ListFeaturedQuestionsRaw,
    ListRelatedQuestionsRaw,
):
    """NOTE:
    This class is auto generated by Konfig (https://konfigthis.com)
    """
    pass
