# coding: utf-8

"""
    StackExchange

    Stack Exchange is a network of 130+ Q&A communities including Stack Overflow. 

    The version of the OpenAPI document: 2.0
    Generated by: https://konfigthis.com
"""

from stack_exchange_python_sdk.paths.tags_tags_faq.get import GetFaqQuestions
from stack_exchange_python_sdk.paths.tags_moderator_only.get import GetModeratorOnlyTagsList
from stack_exchange_python_sdk.paths.tags_tags_related.get import GetRelatedTags
from stack_exchange_python_sdk.paths.tags_tags_info.get import GetTagInfo
from stack_exchange_python_sdk.paths.tags_tags_wikis.get import GetTagWikis
from stack_exchange_python_sdk.paths.tags_tag_top_askers_period.get import GetTopAskersByPeriod
from stack_exchange_python_sdk.paths.me_tags.get import GetUserTagsList
from stack_exchange_python_sdk.paths.me_tags_tags_top_questions.get import GetUserTopQuestions
from stack_exchange_python_sdk.paths.me_top_question_tags.get import GetUserTopTagsList
from stack_exchange_python_sdk.paths.tags_required.get import ListRequiredTags
from stack_exchange_python_sdk.paths.tags_tags_synonyms.get import ListSynonyms
from stack_exchange_python_sdk.paths.tags_synonyms.get import SynonymsList
from stack_exchange_python_sdk.apis.tags.tag_api_raw import TagApiRaw


class TagApi(
    GetFaqQuestions,
    GetModeratorOnlyTagsList,
    GetRelatedTags,
    GetTagInfo,
    GetTagWikis,
    GetTopAskersByPeriod,
    GetUserTagsList,
    GetUserTopQuestions,
    GetUserTopTagsList,
    ListRequiredTags,
    ListSynonyms,
    SynonymsList,
):
    """NOTE:
    This class is auto generated by Konfig (https://konfigthis.com)
    """
    raw: TagApiRaw

    def __init__(self, api_client=None):
        super().__init__(api_client)
        self.raw = TagApiRaw(api_client)
