# coding: utf-8

"""
    StackExchange

    Stack Exchange is a network of 130+ Q&A communities including Stack Overflow. 

    The version of the OpenAPI document: 2.0
    Generated by: https://konfigthis.com
"""

from stack_exchange_python_sdk.paths.users_ids_associated.get import GetAssociatedAccountsRaw
from stack_exchange_python_sdk.paths.users_ids_comments.get import GetCommentsByIdsRaw
from stack_exchange_python_sdk.paths.users_ids_favorites.get import GetFavoritesListRaw
from stack_exchange_python_sdk.paths.users_ids_questions_featured.get import GetFeaturedQuestionsRaw
from stack_exchange_python_sdk.paths.users_id_reputation_history_full.get import GetFullReputationHistoryRaw
from stack_exchange_python_sdk.paths.users_id_inbox.get import GetInboxItemsRaw
from stack_exchange_python_sdk.paths.users_id_inbox_unread.get import GetInboxUnreadRaw
from stack_exchange_python_sdk.paths.users_id_notifications.get import GetNotificationsListRaw
from stack_exchange_python_sdk.paths.users_id_privileges.get import GetPrivilegesListRaw
from stack_exchange_python_sdk.paths.users_ids_questions.get import GetQuestionsByUserIdsRaw
from stack_exchange_python_sdk.paths.users_ids_reputation.get import GetReputationChangesRaw
from stack_exchange_python_sdk.paths.users_ids_reputation_history.get import GetReputationHistoryRaw
from stack_exchange_python_sdk.paths.users_ids_suggested_edits.get import GetSuggestedEditsByIdsRaw
from stack_exchange_python_sdk.paths.users_ids_tags.get import GetTagsRaw
from stack_exchange_python_sdk.paths.users_id_top_question_tags.get import GetTopQuestionTagsRaw
from stack_exchange_python_sdk.paths.users_id_tags_tags_top_questions.get import GetTopQuestionsByTagsRaw
from stack_exchange_python_sdk.paths.users_ids_questions_unaccepted.get import GetUnacceptedQuestionsRaw
from stack_exchange_python_sdk.paths.users_ids_questions_unanswered.get import GetUnansweredQuestionsRaw
from stack_exchange_python_sdk.paths.users_id_notifications_unread.get import GetUnreadNotificationsRaw
from stack_exchange_python_sdk.paths.me.get import GetUserRaw
from stack_exchange_python_sdk.paths.users_ids_answers.get import GetUserAnswersListRaw
from stack_exchange_python_sdk.paths.users_ids_comments_toid.get import GetUserCommentsByIdsAndToidRaw
from stack_exchange_python_sdk.paths.users_ids.get import GetUserProfilesByIdsRaw
from stack_exchange_python_sdk.paths.users_ids_timeline.get import GetUserTimelineByIdsRaw
from stack_exchange_python_sdk.paths.users_id_top_answer_tags.get import GetUserTopAnswerTagsRaw
from stack_exchange_python_sdk.paths.users_id_tags_tags_top_answers.get import GetUserTopAnswersRaw
from stack_exchange_python_sdk.paths.users_id_write_permissions.get import GetWritePermissionsRaw
from stack_exchange_python_sdk.paths.users_ids_merges.get import ListAccountMergesRaw
from stack_exchange_python_sdk.paths.users_moderators_elected.get import ListElectedModeratorUsersRaw
from stack_exchange_python_sdk.paths.users_moderators.get import ListModeratorUsersRaw
from stack_exchange_python_sdk.paths.users_ids_questions_no_answers.get import ListNoAnswerQuestionsRaw
from stack_exchange_python_sdk.paths.users_ids_badges.get import ListUserBadgesRaw
from stack_exchange_python_sdk.paths.users.get import ListUsersRaw
from stack_exchange_python_sdk.paths.users_ids_mentioned.get import MentionedCommentsListRaw


class UserApiRaw(
    GetAssociatedAccountsRaw,
    GetCommentsByIdsRaw,
    GetFavoritesListRaw,
    GetFeaturedQuestionsRaw,
    GetFullReputationHistoryRaw,
    GetInboxItemsRaw,
    GetInboxUnreadRaw,
    GetNotificationsListRaw,
    GetPrivilegesListRaw,
    GetQuestionsByUserIdsRaw,
    GetReputationChangesRaw,
    GetReputationHistoryRaw,
    GetSuggestedEditsByIdsRaw,
    GetTagsRaw,
    GetTopQuestionTagsRaw,
    GetTopQuestionsByTagsRaw,
    GetUnacceptedQuestionsRaw,
    GetUnansweredQuestionsRaw,
    GetUnreadNotificationsRaw,
    GetUserRaw,
    GetUserAnswersListRaw,
    GetUserCommentsByIdsAndToidRaw,
    GetUserProfilesByIdsRaw,
    GetUserTimelineByIdsRaw,
    GetUserTopAnswerTagsRaw,
    GetUserTopAnswersRaw,
    GetWritePermissionsRaw,
    ListAccountMergesRaw,
    ListElectedModeratorUsersRaw,
    ListModeratorUsersRaw,
    ListNoAnswerQuestionsRaw,
    ListUserBadgesRaw,
    ListUsersRaw,
    MentionedCommentsListRaw,
):
    """NOTE:
    This class is auto generated by Konfig (https://konfigthis.com)
    """
    pass
