# coding: utf-8

"""
    StackExchange

    Stack Exchange is a network of 130+ Q&A communities including Stack Overflow. 

    The version of the OpenAPI document: 2.0
    Generated by: https://konfigthis.com
"""

import unittest
from unittest.mock import patch

import urllib3

import stack_exchange_python_sdk
from stack_exchange_python_sdk.paths.me_tags import get
from stack_exchange_python_sdk import configuration, schemas, api_client

from .. import ApiTestMixin


class TestMeTags(ApiTestMixin, unittest.TestCase):
    """
    MeTags unit test stubs
    """

    def setUp(self):
        pass

    def tearDown(self):
        pass

    response_status = 200




if __name__ == '__main__':
    unittest.main()
