# coding: utf-8

"""
    StackExchange

    Stack Exchange is a network of 130+ Q&A communities including Stack Overflow. 

    The version of the OpenAPI document: 2.0
    Generated by: https://konfigthis.com
"""

from dataclasses import dataclass
import typing_extensions
import urllib3
from pydantic import RootModel
from stack_exchange_python_sdk.request_before_hook import request_before_hook
import json
from urllib3._collections import HTTPHeaderDict

from stack_exchange_python_sdk.api_response import AsyncGeneratorResponse
from stack_exchange_python_sdk import api_client, exceptions
from datetime import date, datetime  # noqa: F401
import decimal  # noqa: F401
import functools  # noqa: F401
import io  # noqa: F401
import re  # noqa: F401
import typing  # noqa: F401
import typing_extensions  # noqa: F401
import uuid  # noqa: F401

import frozendict  # noqa: F401

from stack_exchange_python_sdk import schemas  # noqa: F401

from stack_exchange_python_sdk.model.badges import Badges as BadgesSchema

from stack_exchange_python_sdk.type.badges import Badges

from ...api_client import Dictionary
from stack_exchange_python_sdk.pydantic.badges import Badges as BadgesPydantic

# Query params


class OrderSchema(
    schemas.EnumBase,
    schemas.StrSchema
):
    
    @schemas.classproperty
    def DESC(cls):
        return cls("desc")
    
    @schemas.classproperty
    def ASC(cls):
        return cls("asc")
MaxSchema = schemas.StrSchema
MinSchema = schemas.StrSchema


class SortSchema(
    schemas.EnumBase,
    schemas.StrSchema
):
    
    @schemas.classproperty
    def RANK(cls):
        return cls("rank")
    
    @schemas.classproperty
    def NAME(cls):
        return cls("name")
    
    @schemas.classproperty
    def TYPE(cls):
        return cls("type")
FromdateSchema = schemas.IntSchema
TodateSchema = schemas.IntSchema
PagesizeSchema = schemas.IntSchema
PageSchema = schemas.IntSchema
FilterSchema = schemas.StrSchema
CallbackSchema = schemas.StrSchema
SiteSchema = schemas.StrSchema
RequestRequiredQueryParams = typing_extensions.TypedDict(
    'RequestRequiredQueryParams',
    {
        'site': typing.Union[SiteSchema, str, ],
    }
)
RequestOptionalQueryParams = typing_extensions.TypedDict(
    'RequestOptionalQueryParams',
    {
        'order': typing.Union[OrderSchema, str, ],
        'max': typing.Union[MaxSchema, str, ],
        'min': typing.Union[MinSchema, str, ],
        'sort': typing.Union[SortSchema, str, ],
        'fromdate': typing.Union[FromdateSchema, decimal.Decimal, int, ],
        'todate': typing.Union[TodateSchema, decimal.Decimal, int, ],
        'pagesize': typing.Union[PagesizeSchema, decimal.Decimal, int, ],
        'page': typing.Union[PageSchema, decimal.Decimal, int, ],
        'filter': typing.Union[FilterSchema, str, ],
        'callback': typing.Union[CallbackSchema, str, ],
    },
    total=False
)


class RequestQueryParams(RequestRequiredQueryParams, RequestOptionalQueryParams):
    pass


request_query_order = api_client.QueryParameter(
    name="order",
    style=api_client.ParameterStyle.FORM,
    schema=OrderSchema,
    explode=True,
)
request_query_max = api_client.QueryParameter(
    name="max",
    style=api_client.ParameterStyle.FORM,
    schema=MaxSchema,
    explode=True,
)
request_query_min = api_client.QueryParameter(
    name="min",
    style=api_client.ParameterStyle.FORM,
    schema=MinSchema,
    explode=True,
)
request_query_sort = api_client.QueryParameter(
    name="sort",
    style=api_client.ParameterStyle.FORM,
    schema=SortSchema,
    explode=True,
)
request_query_fromdate = api_client.QueryParameter(
    name="fromdate",
    style=api_client.ParameterStyle.FORM,
    schema=FromdateSchema,
    explode=True,
)
request_query_todate = api_client.QueryParameter(
    name="todate",
    style=api_client.ParameterStyle.FORM,
    schema=TodateSchema,
    explode=True,
)
request_query_pagesize = api_client.QueryParameter(
    name="pagesize",
    style=api_client.ParameterStyle.FORM,
    schema=PagesizeSchema,
    explode=True,
)
request_query_page = api_client.QueryParameter(
    name="page",
    style=api_client.ParameterStyle.FORM,
    schema=PageSchema,
    explode=True,
)
request_query_filter = api_client.QueryParameter(
    name="filter",
    style=api_client.ParameterStyle.FORM,
    schema=FilterSchema,
    explode=True,
)
request_query_param_callback = api_client.QueryParameter(
    name="callback",
    style=api_client.ParameterStyle.FORM,
    schema=CallbackSchema,
    explode=True,
)
request_query_site = api_client.QueryParameter(
    name="site",
    style=api_client.ParameterStyle.FORM,
    schema=SiteSchema,
    required=True,
    explode=True,
)
# Path params
IdsSchema = schemas.StrSchema
RequestRequiredPathParams = typing_extensions.TypedDict(
    'RequestRequiredPathParams',
    {
        'ids': typing.Union[IdsSchema, str, ],
    }
)
RequestOptionalPathParams = typing_extensions.TypedDict(
    'RequestOptionalPathParams',
    {
    },
    total=False
)


class RequestPathParams(RequestRequiredPathParams, RequestOptionalPathParams):
    pass


request_path_ids = api_client.PathParameter(
    name="ids",
    style=api_client.ParameterStyle.SIMPLE,
    schema=IdsSchema,
    required=True,
)
SchemaFor200ResponseBody = BadgesSchema


@dataclass
class ApiResponseFor200(api_client.ApiResponse):
    body: Badges


@dataclass
class ApiResponseFor200Async(api_client.AsyncApiResponse):
    body: Badges


_response_for_200 = api_client.OpenApiResponse(
    response_cls=ApiResponseFor200,
    response_cls_async=ApiResponseFor200Async,
    content={
        '*/*': api_client.MediaType(
            schema=SchemaFor200ResponseBody),
    },
)


@dataclass
class ApiResponseFor400(api_client.ApiResponse):
    body: schemas.Unset = schemas.unset


@dataclass
class ApiResponseFor400Async(api_client.AsyncApiResponse):
    body: schemas.Unset = schemas.unset


_response_for_400 = api_client.OpenApiResponse(
    response_cls=ApiResponseFor400,
    response_cls_async=ApiResponseFor400Async,
)


@dataclass
class ApiResponseFor401(api_client.ApiResponse):
    body: schemas.Unset = schemas.unset


@dataclass
class ApiResponseFor401Async(api_client.AsyncApiResponse):
    body: schemas.Unset = schemas.unset


_response_for_401 = api_client.OpenApiResponse(
    response_cls=ApiResponseFor401,
    response_cls_async=ApiResponseFor401Async,
)


@dataclass
class ApiResponseFor402(api_client.ApiResponse):
    body: schemas.Unset = schemas.unset


@dataclass
class ApiResponseFor402Async(api_client.AsyncApiResponse):
    body: schemas.Unset = schemas.unset


_response_for_402 = api_client.OpenApiResponse(
    response_cls=ApiResponseFor402,
    response_cls_async=ApiResponseFor402Async,
)


@dataclass
class ApiResponseFor403(api_client.ApiResponse):
    body: schemas.Unset = schemas.unset


@dataclass
class ApiResponseFor403Async(api_client.AsyncApiResponse):
    body: schemas.Unset = schemas.unset


_response_for_403 = api_client.OpenApiResponse(
    response_cls=ApiResponseFor403,
    response_cls_async=ApiResponseFor403Async,
)


@dataclass
class ApiResponseFor404(api_client.ApiResponse):
    body: schemas.Unset = schemas.unset


@dataclass
class ApiResponseFor404Async(api_client.AsyncApiResponse):
    body: schemas.Unset = schemas.unset


_response_for_404 = api_client.OpenApiResponse(
    response_cls=ApiResponseFor404,
    response_cls_async=ApiResponseFor404Async,
)


@dataclass
class ApiResponseFor405(api_client.ApiResponse):
    body: schemas.Unset = schemas.unset


@dataclass
class ApiResponseFor405Async(api_client.AsyncApiResponse):
    body: schemas.Unset = schemas.unset


_response_for_405 = api_client.OpenApiResponse(
    response_cls=ApiResponseFor405,
    response_cls_async=ApiResponseFor405Async,
)


@dataclass
class ApiResponseFor406(api_client.ApiResponse):
    body: schemas.Unset = schemas.unset


@dataclass
class ApiResponseFor406Async(api_client.AsyncApiResponse):
    body: schemas.Unset = schemas.unset


_response_for_406 = api_client.OpenApiResponse(
    response_cls=ApiResponseFor406,
    response_cls_async=ApiResponseFor406Async,
)


@dataclass
class ApiResponseFor500(api_client.ApiResponse):
    body: schemas.Unset = schemas.unset


@dataclass
class ApiResponseFor500Async(api_client.AsyncApiResponse):
    body: schemas.Unset = schemas.unset


_response_for_500 = api_client.OpenApiResponse(
    response_cls=ApiResponseFor500,
    response_cls_async=ApiResponseFor500Async,
)


@dataclass
class ApiResponseFor502(api_client.ApiResponse):
    body: schemas.Unset = schemas.unset


@dataclass
class ApiResponseFor502Async(api_client.AsyncApiResponse):
    body: schemas.Unset = schemas.unset


_response_for_502 = api_client.OpenApiResponse(
    response_cls=ApiResponseFor502,
    response_cls_async=ApiResponseFor502Async,
)


@dataclass
class ApiResponseFor503(api_client.ApiResponse):
    body: schemas.Unset = schemas.unset


@dataclass
class ApiResponseFor503Async(api_client.AsyncApiResponse):
    body: schemas.Unset = schemas.unset


_response_for_503 = api_client.OpenApiResponse(
    response_cls=ApiResponseFor503,
    response_cls_async=ApiResponseFor503Async,
)
_all_accept_content_types = (
    '*/*',
)


class BaseApi(api_client.Api):

    def _get_badges_by_ids_mapped_args(
        self,
        ids: str,
        site: str,
        order: typing.Optional[str] = None,
        max: typing.Optional[str] = None,
        min: typing.Optional[str] = None,
        sort: typing.Optional[str] = None,
        fromdate: typing.Optional[int] = None,
        todate: typing.Optional[int] = None,
        pagesize: typing.Optional[int] = None,
        page: typing.Optional[int] = None,
        filter: typing.Optional[str] = None,
        param_callback: typing.Optional[str] = None,
    ) -> api_client.MappedArgs:
        args: api_client.MappedArgs = api_client.MappedArgs()
        _query_params = {}
        _path_params = {}
        if order is not None:
            _query_params["order"] = order
        if max is not None:
            _query_params["max"] = max
        if min is not None:
            _query_params["min"] = min
        if sort is not None:
            _query_params["sort"] = sort
        if fromdate is not None:
            _query_params["fromdate"] = fromdate
        if todate is not None:
            _query_params["todate"] = todate
        if pagesize is not None:
            _query_params["pagesize"] = pagesize
        if page is not None:
            _query_params["page"] = page
        if filter is not None:
            _query_params["filter"] = filter
        if param_callback is not None:
            _query_params["callback"] = param_callback
        if site is not None:
            _query_params["site"] = site
        if ids is not None:
            _path_params["ids"] = ids
        args.query = _query_params
        args.path = _path_params
        return args

    async def _aget_badges_by_ids_oapg(
        self,
            query_params: typing.Optional[dict] = {},
            path_params: typing.Optional[dict] = {},
        skip_deserialization: bool = True,
        timeout: typing.Optional[typing.Union[float, typing.Tuple]] = None,
        accept_content_types: typing.Tuple[str] = _all_accept_content_types,
        stream: bool = False,
        **kwargs,
    ) -> typing.Union[
        ApiResponseFor200Async,
        api_client.ApiResponseWithoutDeserializationAsync,
        AsyncGeneratorResponse,
    ]:
        """
        :param skip_deserialization: If true then api_response.response will be set but
            api_response.body and api_response.headers will not be deserialized into schema
            class instances
        """
        self._verify_typed_dict_inputs_oapg(RequestQueryParams, query_params)
        self._verify_typed_dict_inputs_oapg(RequestPathParams, path_params)
        used_path = path.value
    
        _path_params = {}
        for parameter in (
            request_path_ids,
        ):
            parameter_data = path_params.get(parameter.name, schemas.unset)
            if parameter_data is schemas.unset:
                continue
            serialized_data = parameter.serialize(parameter_data)
            _path_params.update(serialized_data)
    
        for k, v in _path_params.items():
            used_path = used_path.replace('{%s}' % k, v)
    
        prefix_separator_iterator = None
        for parameter in (
            request_query_order,
            request_query_max,
            request_query_min,
            request_query_sort,
            request_query_fromdate,
            request_query_todate,
            request_query_pagesize,
            request_query_page,
            request_query_filter,
            request_query_param_callback,
            request_query_site,
        ):
            parameter_data = query_params.get(parameter.name, schemas.unset)
            if parameter_data is schemas.unset:
                continue
            if prefix_separator_iterator is None:
                prefix_separator_iterator = parameter.get_prefix_separator_iterator()
            serialized_data = parameter.serialize(parameter_data, prefix_separator_iterator)
            for serialized_value in serialized_data.values():
                used_path += serialized_value
    
        _headers = HTTPHeaderDict()
        # TODO add cookie handling
        if accept_content_types:
            for accept_content_type in accept_content_types:
                _headers.add('Accept', accept_content_type)
        method = 'get'.upper()
        request_before_hook(
            resource_path=used_path,
            method=method,
            configuration=self.api_client.configuration,
            path_template='/badges/{ids}',
            headers=_headers,
        )
    
        response = await self.api_client.async_call_api(
            resource_path=used_path,
            method=method,
            headers=_headers,
            prefix_separator_iterator=prefix_separator_iterator,
            timeout=timeout,
            **kwargs
        )
    
        if stream:
            if not 200 <= response.http_response.status <= 299:
                body = (await response.http_response.content.read()).decode("utf-8")
                raise exceptions.ApiStreamingException(
                    status=response.http_response.status,
                    reason=response.http_response.reason,
                    body=body,
                )
    
            async def stream_iterator():
                """
                iterates over response.http_response.content and closes connection once iteration has finished
                """
                async for line in response.http_response.content:
                    if line == b'\r\n':
                        continue
                    yield line
                response.http_response.close()
                await response.session.close()
            return AsyncGeneratorResponse(
                content=stream_iterator(),
                headers=response.http_response.headers,
                status=response.http_response.status,
                response=response.http_response
            )
    
        response_for_status = _status_code_to_response.get(str(response.http_response.status))
        if response_for_status:
            api_response = await response_for_status.deserialize_async(
                                                    response,
                                                    self.api_client.configuration,
                                                    skip_deserialization=skip_deserialization
                                                )
        else:
            # If response data is JSON then deserialize for SDK consumer convenience
            is_json = api_client.JSONDetector._content_type_is_json(response.http_response.headers.get('Content-Type', ''))
            api_response = api_client.ApiResponseWithoutDeserializationAsync(
                body=await response.http_response.json() if is_json else await response.http_response.text(),
                response=response.http_response,
                round_trip_time=response.round_trip_time,
                status=response.http_response.status,
                headers=response.http_response.headers,
            )
    
        if not 200 <= api_response.status <= 299:
            raise exceptions.ApiException(api_response=api_response)
    
        # cleanup session / response
        response.http_response.close()
        await response.session.close()
    
        return api_response


    def _get_badges_by_ids_oapg(
        self,
            query_params: typing.Optional[dict] = {},
            path_params: typing.Optional[dict] = {},
        skip_deserialization: bool = True,
        timeout: typing.Optional[typing.Union[float, typing.Tuple]] = None,
        accept_content_types: typing.Tuple[str] = _all_accept_content_types,
        stream: bool = False,
    ) -> typing.Union[
        ApiResponseFor200,
        api_client.ApiResponseWithoutDeserialization,
    ]:
        """
        :param skip_deserialization: If true then api_response.response will be set but
            api_response.body and api_response.headers will not be deserialized into schema
            class instances
        """
        self._verify_typed_dict_inputs_oapg(RequestQueryParams, query_params)
        self._verify_typed_dict_inputs_oapg(RequestPathParams, path_params)
        used_path = path.value
    
        _path_params = {}
        for parameter in (
            request_path_ids,
        ):
            parameter_data = path_params.get(parameter.name, schemas.unset)
            if parameter_data is schemas.unset:
                continue
            serialized_data = parameter.serialize(parameter_data)
            _path_params.update(serialized_data)
    
        for k, v in _path_params.items():
            used_path = used_path.replace('{%s}' % k, v)
    
        prefix_separator_iterator = None
        for parameter in (
            request_query_order,
            request_query_max,
            request_query_min,
            request_query_sort,
            request_query_fromdate,
            request_query_todate,
            request_query_pagesize,
            request_query_page,
            request_query_filter,
            request_query_param_callback,
            request_query_site,
        ):
            parameter_data = query_params.get(parameter.name, schemas.unset)
            if parameter_data is schemas.unset:
                continue
            if prefix_separator_iterator is None:
                prefix_separator_iterator = parameter.get_prefix_separator_iterator()
            serialized_data = parameter.serialize(parameter_data, prefix_separator_iterator)
            for serialized_value in serialized_data.values():
                used_path += serialized_value
    
        _headers = HTTPHeaderDict()
        # TODO add cookie handling
        if accept_content_types:
            for accept_content_type in accept_content_types:
                _headers.add('Accept', accept_content_type)
        method = 'get'.upper()
        request_before_hook(
            resource_path=used_path,
            method=method,
            configuration=self.api_client.configuration,
            path_template='/badges/{ids}',
            headers=_headers,
        )
    
        response = self.api_client.call_api(
            resource_path=used_path,
            method=method,
            headers=_headers,
            prefix_separator_iterator=prefix_separator_iterator,
            timeout=timeout,
        )
    
        response_for_status = _status_code_to_response.get(str(response.http_response.status))
        if response_for_status:
            api_response = response_for_status.deserialize(
                                                    response,
                                                    self.api_client.configuration,
                                                    skip_deserialization=skip_deserialization
                                                )
        else:
            # If response data is JSON then deserialize for SDK consumer convenience
            is_json = api_client.JSONDetector._content_type_is_json(response.http_response.headers.get('Content-Type', ''))
            api_response = api_client.ApiResponseWithoutDeserialization(
                body=json.loads(response.http_response.data) if is_json else response.http_response.data,
                response=response.http_response,
                round_trip_time=response.round_trip_time,
                status=response.http_response.status,
                headers=response.http_response.headers,
            )
    
        if not 200 <= api_response.status <= 299:
            raise exceptions.ApiException(api_response=api_response)
    
        return api_response


class GetBadgesByIdsRaw(BaseApi):
    # this class is used by api classes that refer to endpoints with operationId fn names

    async def aget_badges_by_ids(
        self,
        ids: str,
        site: str,
        order: typing.Optional[str] = None,
        max: typing.Optional[str] = None,
        min: typing.Optional[str] = None,
        sort: typing.Optional[str] = None,
        fromdate: typing.Optional[int] = None,
        todate: typing.Optional[int] = None,
        pagesize: typing.Optional[int] = None,
        page: typing.Optional[int] = None,
        filter: typing.Optional[str] = None,
        param_callback: typing.Optional[str] = None,
        **kwargs,
    ) -> typing.Union[
        ApiResponseFor200Async,
        api_client.ApiResponseWithoutDeserializationAsync,
        AsyncGeneratorResponse,
    ]:
        args = self._get_badges_by_ids_mapped_args(
            ids=ids,
            site=site,
            order=order,
            max=max,
            min=min,
            sort=sort,
            fromdate=fromdate,
            todate=todate,
            pagesize=pagesize,
            page=page,
            filter=filter,
            param_callback=param_callback,
        )
        return await self._aget_badges_by_ids_oapg(
            query_params=args.query,
            path_params=args.path,
            **kwargs,
        )
    
    def get_badges_by_ids(
        self,
        ids: str,
        site: str,
        order: typing.Optional[str] = None,
        max: typing.Optional[str] = None,
        min: typing.Optional[str] = None,
        sort: typing.Optional[str] = None,
        fromdate: typing.Optional[int] = None,
        todate: typing.Optional[int] = None,
        pagesize: typing.Optional[int] = None,
        page: typing.Optional[int] = None,
        filter: typing.Optional[str] = None,
        param_callback: typing.Optional[str] = None,
    ) -> typing.Union[
        ApiResponseFor200,
        api_client.ApiResponseWithoutDeserialization,
    ]:
        args = self._get_badges_by_ids_mapped_args(
            ids=ids,
            site=site,
            order=order,
            max=max,
            min=min,
            sort=sort,
            fromdate=fromdate,
            todate=todate,
            pagesize=pagesize,
            page=page,
            filter=filter,
            param_callback=param_callback,
        )
        return self._get_badges_by_ids_oapg(
            query_params=args.query,
            path_params=args.path,
        )

class GetBadgesByIds(BaseApi):

    async def aget_badges_by_ids(
        self,
        ids: str,
        site: str,
        order: typing.Optional[str] = None,
        max: typing.Optional[str] = None,
        min: typing.Optional[str] = None,
        sort: typing.Optional[str] = None,
        fromdate: typing.Optional[int] = None,
        todate: typing.Optional[int] = None,
        pagesize: typing.Optional[int] = None,
        page: typing.Optional[int] = None,
        filter: typing.Optional[str] = None,
        param_callback: typing.Optional[str] = None,
        validate: bool = False,
        **kwargs,
    ) -> BadgesPydantic:
        raw_response = await self.raw.aget_badges_by_ids(
            ids=ids,
            site=site,
            order=order,
            max=max,
            min=min,
            sort=sort,
            fromdate=fromdate,
            todate=todate,
            pagesize=pagesize,
            page=page,
            filter=filter,
            param_callback=param_callback,
            **kwargs,
        )
        if validate:
            return RootModel[BadgesPydantic](raw_response.body).root
        return api_client.construct_model_instance(BadgesPydantic, raw_response.body)
    
    
    def get_badges_by_ids(
        self,
        ids: str,
        site: str,
        order: typing.Optional[str] = None,
        max: typing.Optional[str] = None,
        min: typing.Optional[str] = None,
        sort: typing.Optional[str] = None,
        fromdate: typing.Optional[int] = None,
        todate: typing.Optional[int] = None,
        pagesize: typing.Optional[int] = None,
        page: typing.Optional[int] = None,
        filter: typing.Optional[str] = None,
        param_callback: typing.Optional[str] = None,
        validate: bool = False,
    ) -> BadgesPydantic:
        raw_response = self.raw.get_badges_by_ids(
            ids=ids,
            site=site,
            order=order,
            max=max,
            min=min,
            sort=sort,
            fromdate=fromdate,
            todate=todate,
            pagesize=pagesize,
            page=page,
            filter=filter,
            param_callback=param_callback,
        )
        if validate:
            return RootModel[BadgesPydantic](raw_response.body).root
        return api_client.construct_model_instance(BadgesPydantic, raw_response.body)


class ApiForget(BaseApi):
    # this class is used by api classes that refer to endpoints by path and http method names

    async def aget(
        self,
        ids: str,
        site: str,
        order: typing.Optional[str] = None,
        max: typing.Optional[str] = None,
        min: typing.Optional[str] = None,
        sort: typing.Optional[str] = None,
        fromdate: typing.Optional[int] = None,
        todate: typing.Optional[int] = None,
        pagesize: typing.Optional[int] = None,
        page: typing.Optional[int] = None,
        filter: typing.Optional[str] = None,
        param_callback: typing.Optional[str] = None,
        **kwargs,
    ) -> typing.Union[
        ApiResponseFor200Async,
        api_client.ApiResponseWithoutDeserializationAsync,
        AsyncGeneratorResponse,
    ]:
        args = self._get_badges_by_ids_mapped_args(
            ids=ids,
            site=site,
            order=order,
            max=max,
            min=min,
            sort=sort,
            fromdate=fromdate,
            todate=todate,
            pagesize=pagesize,
            page=page,
            filter=filter,
            param_callback=param_callback,
        )
        return await self._aget_badges_by_ids_oapg(
            query_params=args.query,
            path_params=args.path,
            **kwargs,
        )
    
    def get(
        self,
        ids: str,
        site: str,
        order: typing.Optional[str] = None,
        max: typing.Optional[str] = None,
        min: typing.Optional[str] = None,
        sort: typing.Optional[str] = None,
        fromdate: typing.Optional[int] = None,
        todate: typing.Optional[int] = None,
        pagesize: typing.Optional[int] = None,
        page: typing.Optional[int] = None,
        filter: typing.Optional[str] = None,
        param_callback: typing.Optional[str] = None,
    ) -> typing.Union[
        ApiResponseFor200,
        api_client.ApiResponseWithoutDeserialization,
    ]:
        args = self._get_badges_by_ids_mapped_args(
            ids=ids,
            site=site,
            order=order,
            max=max,
            min=min,
            sort=sort,
            fromdate=fromdate,
            todate=todate,
            pagesize=pagesize,
            page=page,
            filter=filter,
            param_callback=param_callback,
        )
        return self._get_badges_by_ids_oapg(
            query_params=args.query,
            path_params=args.path,
        )

